name: linkv_sdk
description: LINKV SDK for the DART programming language.
version: 0.4.2
homepage: https://www.linkv.sg
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  ffi: ^0.1.3
  pool: ^1.4.0
  dio: ^3.0.9
  convert: ^2.1.1
  crypto: ^2.1.5
dev_dependencies:
  pedantic: ^1.8.0